version: "3"

tasks:
  setup:
    cmds:
      - stow -R -t ~ --ignore="Taskfile.yaml" zsh
      - task: syntax-highlighting
    status:
      - test -f ~/.zshrc
      - test -f ~/.zsh/catppuccin_mocha-zsh-syntax-highlighting.zsh

  clean:
    cmds:
      - stow -t ~ -D zsh

  syntax-highlighting:
    cmds:
      - mkdir -p ~/.zsh
      - curl -o ~/.zsh/catppuccin_mocha-zsh-syntax-highlighting.zsh https://raw.githubusercontent.com/catppuccin/zsh-syntax-highlighting/main/themes/catppuccin_mocha-zsh-syntax-highlighting.zsh
    status:
      - test -d ~/.zsh
      - test -f ~/.zsh/catppuccin_mocha-zsh-syntax-highlighting.zsh
